FROM nginx:1.27-alpine

COPY landing.html /usr/share/nginx/html/landing.html
COPY landing.css /usr/share/nginx/html/landing.css
COPY ui.css /usr/share/nginx/html/ui.css
COPY styles.css /usr/share/nginx/html/styles.css
COPY index.html /usr/share/nginx/html/index.html
COPY backoffice.html /usr/share/nginx/html/backoffice.html
COPY admin.html /usr/share/nginx/html/admin.html
COPY profesor.html /usr/share/nginx/html/profesor.html
COPY alumno.html /usr/share/nginx/html/alumno.html
COPY pago.html /usr/share/nginx/html/pago.html
COPY swagger.html /usr/share/nginx/html/swagger.html
COPY app.js /usr/share/nginx/html/app.js
COPY chatbot.js /usr/share/nginx/html/chatbot.js
COPY session-telemetry.js /usr/share/nginx/html/session-telemetry.js
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY sitemap.xml /usr/share/nginx/html/sitemap.xml
COPY llms.txt /usr/share/nginx/html/llms.txt

EXPOSE 80
