package com.micuota.mvp.domain;

public enum PaymentEventType {
    PAYMENT_CREATED,
    PAYMENT_LINK_SENT,
    WEBHOOK_RECEIVED,
    PAYMENT_STATUS_CHANGED,
    REMINDER_SENT,
    RETRY_SCHEDULED,
    DEBT_MARKED,
    RECONCILIATION_MATCHED,
    RECONCILIATION_MISMATCHED
}
