spring.datasource.url=jdbc:h2:file:./data/micuota;MODE=PostgreSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS CRM\\;CREATE SCHEMA IF NOT EXISTS ANALYTICS
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false
app.demo-seed.enabled=true

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:false}

app.mail.from=${MAIL_FROM:no-reply@micuota.online}
